[versions]
activity-compose = "1.8.2"
agp = "8.2.2"
appcompat = "1.6.1"
coilComposeVersion = "2.5.0"
core-ktx = "1.12.0"
compose-bom = "2023.10.01"
gsonVersion = "2.10.1"
koinVersion = "3.5.3"
kotlin = "1.9.20"
kotlinxCoroutinesCoreVersion = "1.7.3"
ktlint = "12.1.0"
ksp-plugin="1.9.20-1.0.14"
navigation-compose = "2.7.6"
okhttp = "4.11.0"
pagingComposeVersion = "3.2.1"
retrofitVersion = "2.9.0"
roomVersion = "2.6.1"
lifecycle-viewmodel-compose = "2.7.0"
lifecycle-runtime-ktx = "2.7.0"
material = "1.11.0"

[libraries]

# AndroidX
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "core-ktx" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation-compose" }
androidx-paging-compose = { module = "androidx.paging:paging-compose", version.ref = "pagingComposeVersion" }
androidx-paging-runtime = { module = "androidx.paging:paging-runtime-ktx", version.ref = "pagingComposeVersion" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomVersion" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "roomVersion" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomVersion" }
androidx-room-paging = { module = "androidx.room:room-paging", version.ref = "roomVersion" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle-runtime-ktx" }

# Compose
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "compose-bom" }
compose-ui = { group = "androidx.compose.ui", name = "ui" }
compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
compose-material3 = { group = "androidx.compose.material3", name = "material3" }
compose-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }

# Coil
compose-coil = { module = "io.coil-kt:coil-compose", version.ref = "coilComposeVersion" }

# Koin
koin-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koinVersion" }

# GSON
gson = { module = "com.google.code.gson:gson", version.ref = "gsonVersion" }

# KotlinX
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutinesCoreVersion" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutinesCoreVersion" }

# Material
material = { module = "com.google.android.material:material", version.ref = "material" }

# OkHttp
okhttp3-bom = { module = "com.squareup.okhttp3:okhttp-bom", version.ref = "okhttp" }
okhttp3 = {group="com.squareup.okhttp3", name="okhttp"}
okhttp3-logging-interceptor={group="com.squareup.okhttp3", name="logging-interceptor"}

# Retrofit
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofitVersion" }
retrofit-converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofitVersion" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp-plugin" }
