[versions]
accompanistPermissions = "0.32.0"
acra = "5.11.2"
activityCompose = "1.8.0"
agp = "8.1.3"
amplituda = "2.2.2"
appcompat = "1.6.1"
appUpdateKtx = "2.1.0"
appUpdate = "2.1.0"
camposer = "0.2.2"
coil-compose = "2.4.0"
compose-bom = "2023.10.01"
compose-markdown = "0.3.3"
compose-scrollbars = "1.0.3"
coreKtx = "1.12.0"
coreSplashscreen = "1.0.1"
datastorePreferences= "1.0.0"
desugar_jdk_libs = "2.0.4"
firebaseBOM = "32.5.0"
gson = "2.10.1"
hilt = "2.48"
hiltNavigationCompose = "1.1.0"
junit = "4.13.2"
jwtdecode = "2.0.2"
kotlin = "1.8.10"
crashlytics = "2.9.5"
gms = "4.3.15"
ktlint = "11.3.2"
ksp-plugin = "1.8.10-1.0.9" # dependent on kotlin version
leakcanary-android = "2.12"
lifecycleRuntimeKtx = "2.6.2"
media3 = "1.1.1"
multidex = "2.0.1"
okhttp = "5.0.0-alpha.2"
onnxruntimeAndroid = "1.15.1"
pytorch_android_torchvision_lite = "1.13.1"
pytorch_android_lite = "1.13.1"
rawaudiorecorder = "0.0.4"
retrofit = "2.9.0"
room = "2.5.2"
runtimeLivedata = "1.5.4"
workRuntimeKtx = "2.8.1"
zoomable = "1.6.1"
timber = "5.0.1"
androidx-test-ext-junit = "1.1.5"
espresso-core = "3.5.1"
material = "1.10.0"
org-jetbrains-kotlin-jvm = "1.8.10"

[libraries]
accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanistPermissions" }
acra-toast = { module = "ch.acra:acra-toast", version.ref = "acra" }
acra-http = { module = "ch.acra:acra-http", version.ref = "acra" }
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
amplituda = { module = "com.github.lincollincol:amplituda", version.ref = "amplituda" }
app-update-ktx = { module = "com.google.android.play:app-update-ktx", version.ref = "appUpdateKtx" }
app-update = { module = "com.google.android.play:app-update", version.ref = "appUpdate" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
camposer = { module = "io.github.ujizin:camposer", version.ref = "camposer" }

# Compose
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "compose-bom" }
compose-ui = { group = "androidx.compose.ui", name = "ui" }
compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
compose-material3 = { group = "androidx.compose.material3", name = "material3" }
compose-runtime-livedata = { module = "androidx.compose.runtime:runtime-livedata", version.ref = "runtimeLivedata" }
compose-markdown = { module = "com.github.jeziellago:compose-markdown", version.ref = "compose-markdown" }
compose-scrollbars = { module = "com.github.GIGAMOLE:ComposeScrollbars", version.ref = "compose-scrollbars" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil-compose" }

# AndroidX core
core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "coreSplashscreen" }

# DataStore
datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastorePreferences" }

desugar_jdk_libs = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar_jdk_libs" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }

# Dagger-Hilt
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltNavigationCompose" }

# Firebase
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebaseBOM" }
firebase-messaging-ktx = { group = "com.google.firebase", name = "firebase-messaging-ktx" }
firebase-crashlytics-ktx = { group = "com.google.firebase", name = "firebase-crashlytics-ktx" }
firebase-analytics-ktx = { group = "com.google.firebase", name = "firebase-analytics-ktx" }

junit = { module = "junit:junit", version.ref = "junit" }
jwtdecode = { module = "com.auth0.android:jwtdecode", version.ref = "jwtdecode" }
leakcanary-android = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "leakcanary-android" }
lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }

# Media3
media3-exoplayer = { module = "androidx.media3:media3-exoplayer", version.ref = "media3" }
media3-exoplayer-dash = { module = "androidx.media3:media3-exoplayer-dash", version.ref = "media3" }
media3-datasource-cronet = { module = "androidx.media3:media3-datasource-cronet", version.ref = "media3" }
media3-ui = { module = "androidx.media3:media3-ui", version.ref = "media3" }

multidex = { module = "androidx.multidex:multidex", version.ref = "multidex" }

# OkHttp
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttp-logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }

onnxruntime-android = { module = "com.microsoft.onnxruntime:onnxruntime-android", version.ref = "onnxruntimeAndroid" }
pytorch_android_torchvision_lite = { module = "org.pytorch:pytorch_android_torchvision_lite", version.ref = "pytorch_android_torchvision_lite" }
pytorch_android_lite = { module = "org.pytorch:pytorch_android_lite", version.ref = "pytorch_android_lite" }
rawaudiorecorder = { module = "io.github.karya-inc:rawaudiorecorder", version.ref = "rawaudiorecorder" }

# Retrofit
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }

# Room
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }

work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "workRuntimeKtx" }
zoomable = { module = "com.mxalbert.zoomable:zoomable", version.ref = "zoomable" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
googleServices = { id = "com.google.gms.google-services", version.ref = "gms" }
crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "crashlytics" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp-plugin" }
org-jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "org-jetbrains-kotlin-jvm" }